move ModelRun under FeatureExtraction
DARPA-CRITICALMAAS/schemas pull request #20
Opened 2023-10-18 17:39 UTC by zekun-li

2023-10-24 20:08 UTC, asaxton approved these changes
Looks good to me. But I'm happy to yield to other reviewer.

2023-10-25 14:53 UTC, dgiesbrecht approved these changes

2023-10-25 18:53 UTC, davenquinn requested changes
Looks good, except that duplicated generation code for `output.png` should be removed.

2023-10-25 18:53 UTC, davenquinn commented on ta1/output.py
> +graph = erd.create(Map)
I think this diagram creation code is now duplicative of code in https://github.com/DARPA-CRITICALMAAS/schemas/blob/main/scripts/generate-schema.py. This code  (and the imports that it references) should be deleted for a clean merge.

2023-10-25 18:53 UTC, davenquinn commented on ta1/output.py
> +import erdantic as erd
see comment below

2023-11-01 23:19 UTC, zekun-li commented on ta1/output.py
> +import erdantic as erd
Resolved in the latest commit

2023-11-07 10:00 UTC, merged